version: '3.8'
services:
 
  claim:
    build:
      context: .
      dockerfile: src/Dockerfile
    ports:
      - "8001:8001"
    environment:
      - DB_HOST=192.168.222.163
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=postgres
    depends_on:
      - db
  
  db:
  
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local

